#!/bin/bash

echo "[Pre-Commit] Checking code style"
flake8 src/pystencilssfg
status=$?

if [ ${status} != 0 ]; then
    exit 1
else
    echo "[Pre-Commit] Style OK!"
fi

echo "[Pre-Commit] Checking types"
mypy src/pystencilssfg
status=$?
if [ ${status} != 0 ]; then
    exit 1
else
    echo "[Pre-Commit] Types OK!"
fi
