stages:
  - "Code Quality"
  - "Tests"
  - "Documentation"
  - deploy

.nox-base:
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/nox:alpine
  tags:
    - docker

linter:
  extends: .nox-base
  stage: "Code Quality"
  needs: []
  script:
    - nox --session lint

typechecker:
  extends: .nox-base
  stage: "Code Quality"
  needs: []
  script:
    - nox --session typecheck

.testsuite-base:
  stage: "Tests"
  needs: []
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    when: always
    paths:
      - htmlcov
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

"testsuite-py3.10+cuda":
  extends: .testsuite-base
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/nox:ubuntu24.04-cuda12.6
  script:
    - nox --session testsuite-3.10
  tags:
    - docker
    - cuda
    - cudaComputeCapability6.1

"testsuite-py3.13":
  extends: .testsuite-base
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/nox:alpine
  script:
    - nox --session testsuite-3.13

build-documentation:
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/nox:ubuntu24.04
  stage: "Documentation"
  needs: []
  script:
    - nox -s docs -- --fail-on-warnings
  artifacts:
    paths:
      - docs/build/html
    when: always
  tags:
     - docker

pages:
  image: alpine:latest
  stage: deploy
  script:
    - ls -l
    - mv docs/build/html public  # folder has to be named "public" for gitlab to publish it
  artifacts:
    paths:
      - public
  tags:
    - docker
  only:
    - master@pycodegen/pystencils-sfg

cmake-standalone:
  stage: deploy
  needs: []
  script:
    - echo "Publishing Cmake standalone"
  artifacts:
    paths:
      - standalone
