stages:
  - "Code Quality"
  - "Tests"
  - "Documentation"
  - deploy

.nox-base:
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/nox:alpine
  tags:
    - docker

linter:
  extends: .nox-base
  stage: "Code Quality"
  needs: []
  script:
    - nox --session lint

typechecker:
  extends: .nox-base
  stage: "Code Quality"
  needs: []
  script:
    - nox --session typecheck

testsuite:
  extends: .nox-base
  stage: "Tests"
  needs: []
  script:
    - nox --session testsuite
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    when: always
    paths:
      - htmlcov
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build-documentation:
  extends: .nox-base
  stage: "Documentation"
  needs: []
  script:
    - nox --session docs
  artifacts:
    paths:
      - docs/build/html

pages:
  image: alpine:latest
  stage: deploy
  script:
    - ls -l
    - mv docs/build/html public  # folder has to be named "public" for gitlab to publish it
  artifacts:
    paths:
      - public
  tags:
    - docker
  only:
    - master@pycodegen/pystencils-sfg
