stages:
  - pretest
  - test
  - deploy

linter:
  stage: pretest
  except:
    variables:
      - $ENABLE_NIGHTLY_BUILDS
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
  script:
    - flake8 src/pystencilssfg
  tags:
    - docker

typechecker:
  stage: pretest
  except:
    variables:
      - $ENABLE_NIGHTLY_BUILDS
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
  script:
    - pip install mypy
    - mypy src/pystencilssfg 
  tags:
    - docker

build-documentation:
  stage: test
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
  script:
    - pip install mkdocs mkdocs-material mkdocstrings[python]
    - mkdocs build -v
  tags:
    - docker
  artifacts:
    paths:
      - site

pages:
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
  stage: deploy
  script:
    - ls -l
    - mv site public  # folder has to be named "public" for gitlab to publish it
  artifacts:
    paths:
      - public
  tags:
    - docker
  only:
    - master@da15siwa/pystencils-sfg
