stages:
  - "Code Quality"
  - "Tests"
  - "Documentation"
  - deploy

linter:
  stage: "Code Quality"
  needs: []
  except:
    variables:
      - $ENABLE_NIGHTLY_BUILDS
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
  script:
    - flake8 src/pystencilssfg
  tags:
    - docker

typechecker:
  stage: "Code Quality"
  needs: []
  except:
    variables:
      - $ENABLE_NIGHTLY_BUILDS
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
  script:
    - pip install mypy
    - mypy src/pystencilssfg 
  tags:
    - docker

testsuite:
  stage: "Tests"
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
  needs: []
  tags:
    - docker
  before_script:
    - pip install "git+https://i10git.cs.fau.de/pycodegen/pystencils.git@v2.0-dev"
    - pip install -e .
  script:
    - coverage run -m pytest -v
    - coverage report
    - coverage html
    - coverage xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    when: always
    paths:
      - htmlcov
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build-documentation:
  stage: "Documentation"
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
  needs: []
  before_script:
    - pip install "git+https://i10git.cs.fau.de/pycodegen/pystencils.git@v2.0-dev"
    - pip install -e .[docs]
  script:
    - cd docs
    - make html
  tags:
    - docker
  artifacts:
    paths:
      - docs/build/html

pages:
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
  stage: deploy
  script:
    - ls -l
    - mv docs/build/html public  # folder has to be named "public" for gitlab to publish it
  artifacts:
    paths:
      - public
  tags:
    - docker
  only:
    - master@pycodegen/pystencils-sfg
