site_name: pystencils-sfg Docs
site_author: Frederik Hennig
copyright: © 2023 Frederik Hennig

repo_name: GitLab
repo_url: https://i10git.cs.fau.de/pycodegen/pystencils-sfg


theme: 
  name: material
  features: 
    - navigation.tabs
    - content.code.copy
  palette:
    scheme: slate
    primary: deep purple

extra_css:
 - css/mkdocstrings.css

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            heading_level: 2
            members_order: source
            group_by_category: False
            show_root_heading: True
            show_root_full_path: True
            show_symbol_type_heading: True
            show_symbol_type_toc: True
            show_source: False
            show_signature_annotations: True
            signature_crossrefs: True

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 

nav:
  - Home: index.md
  - 'User Guides':
    - 'Overview': usage/index.md
    - 'Writing Generator Scripts': usage/generator_scripts.md
    - 'In-Depth: Building Source Files': usage/building.md
    - 'CLI and Build System Integration': usage/cli_and_build_system.md
  - 'API Documentation':
    - 'Overview': api/index.md
    - 'Front End':
      - 'Source File Generator': api/generator.md
      - 'Code Generation Context': api/context.md
      - 'Composer': api/composer.md
    - 'Source File Modelling':
      - 'Source File Components': api/source_components.md
      - 'Kernel Call Tree': api/tree.md
    - 'High-Level Language Concepts':
      - 'Base Classes': 'api/source_objects.md'
      - 'C++ Standard Library': 'api/cpp_std.md'
    - 'Code Generation':
      - 'Emission and Printing': api/emission.md
