site_name: pystencils Source File Generator Documentation
theme: 
  name: material

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]


nav:
  - Home: index.md
  - API Documentation: api.md
