[project]
name = "pystencilssfg"
description = "pystencils Source File Generator"
authors = [
    {name = "Frederik Hennig", email = "frederik.hennig@fau.de"},
]
dependencies = [
    "jinja2>=3.1.2",
    "pystencils>=1.3.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "noneyet"}
dynamic = ["version"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.pdm.dev-dependencies]
interactive = [
    "ipython>=8.17.2",
]
