[project]
name = "pystencilssfg"
description = "pystencils Source File Generator"
authors = [
    {name = "Frederik Hennig", email = "frederik.hennig@fau.de"},
]
dependencies = [
    "jinja2>=3.1.2",
    "pystencils>=1.3.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "noneyet"}
dynamic = ["version"]

[build-system]
requires = ["setuptools>=61", "versioneer>=0.29"]
build-backend = "setuptools.build_meta"

[tool.pdm.dev-dependencies]
interactive = [
    "ipython>=8.17.2",
]
dev = [
    "flake8>=6.1.0",
    "mypy>=1.7.0",
]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "src/pystencilssfg/_version.py"
versionfile_build = "pystencilssfg/_version.py"
tag_prefix = ""
parentdir_prefix = "pystencilssfg-"
